### ISSUE TITLE
JVM系列404了

### ISSUE THREAD

**Issue by allenz92** [youthlql/JavaYouth#10]
比如这里：[JVM系列-第1章-JVM与Java体系结构](https://youthlql.gitee.io/javayouth/#/docs/Java/JVM/JVM%E7%B3%BB%E5%88%97-%E7%AC%AC1%E7%AB%A0-JVM%E4%B8%8EJava%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84)

**Comment by youthlql** [comment]
晚上修复下

**Comment by youthlql** [comment]
想起来了，gitee太麻烦了，所以gitee的站点我关了，现在是这里：imlql.cn/javayouth/#/ 
在readme里有写，这个跟gitee速度差不多，
