### ISSUE TITLE
兄弟，你怎么把Java和redis八股删除了呢

### ISSUE THREAD

**Issue by Stan-QRX** [youthlql/JavaYouth#11]
兄弟，你怎么把Java和redis八股删除了呢

**Comment by youthlql** [comment]
没删，在suibi目录里，只是没写在readme里了

**Comment by Stan-QRX** [comment]
GitHub我找到了，兄弟你没事的时候把gitee可以也更新下

**Comment by youthlql** [comment]
gitee文章同步了，但是gitee page比较难用，一直有缓存也不知道怎么回事，所以就没怎么管了。建议github
