### ISSUE TITLE
关于volatile示例的疑问

### ISSUE THREAD

**Issue by MoShQing** [youthlql/JavaYouth#13]
`/* 笔记
 * 1.当没有加Volatile的时候,while循环会一直在里面循环转圈
 * 2.当加了之后Volatile,由于可见性,一旦num改了之后,就会通知其他线程
 * 3.还有注意的时候不能用if,if不会重新拉回来再判断一次。(也叫做虚假唤醒)
 * 4.案例演示:一个线程对共享变量的修改,另一个线程不能立即得到新值
 * */
public class Video04_01 {

    public static void main(String[] args) {
        MyData myData = new MyData();

        new Thread(() ->{
            System.out.println(Thread.currentThread().getName() + "\t come in ");
            try {
                TimeUnit.SECONDS.sleep(3);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            //睡3秒之后再修改num,防止A线程先修改了num,那么到while循环的时候就会直接跳出去了
            myData.addTo60();
            System.out.println(Thread.currentThread().getName() + "\t come out");
        },"A").start();

        while(myData.num == 0){
            //只有当num不等于0的时候,才会跳出循环
        }
    }
}

class MyData{
    int num = 0;

    public void addTo60(){
        this.num = 60;
    }
}`

这个关于volatile的示例，while里是空的话，程序是一直在运行的。但是如果在while里随便加一个输出啥的，程序就会正常结束。请问这个知道是什么原因么

**Comment by youthlql** [comment]
![image](https://user-images.githubusercontent.com/49017153/155257505-2d754bab-2b90-42e4-9274-f031e6add846.png)
![image](https://user-images.githubusercontent.com/49017153/155257542-eb59eb62-6a9c-4f91-b9e4-4851e3fc4f8a.png)
println输出语句里加了synchronized，从操作系统层面来讲synchronized会刷新L1 L2 L3缓存，这样之前mydata.num也被刷出来了，然后就直接都从内存里读取新数据了。

**Comment by MoShQing** [comment]
好的，感谢您的解惑。
