### ISSUE TITLE
检查一下，这个文件 在gitee 上面显示违规，帮忙敏感词删除一下，谢谢

### ISSUE THREAD

**Issue by dazer007** [youthlql/JavaYouth#15]
检查一下，这个文件：https://gitee.com/youthlql/JavaYouth/blob/main/docs/netty/Netty%E5%85%A5%E9%97%A8-%E7%AC%AC%E4%B8%80%E8%AF%9D.md

<img width="797" alt="image" src="https://user-images.githubusercontent.com/6936476/175458219-5a42c21f-fa39-4006-8c90-0f1b7045fcb2.png">

**Comment by youthlql** [comment]
用github吧，gitee限制太多了，敏感词也不给提示，gitee是直接同步github的仓库的

**Comment by dazer007** [comment]
我看已经好了，我给 官方提了issue. 现在解禁了。
