### ISSUE TITLE
JVM笔记中部分图片无法加载

### ISSUE THREAD

**Issue by Anlyjia** [youthlql/JavaYouth#4]
朋友，能把JVM中的image目录也上传一下吗？md文件中有些文件打不开

**Comment by youthlql** [comment]
具体哪几篇呢？可以具体说一下吗，有可能是之前传漏了

**Comment by Anlyjia** [comment]
第二章
![image](https://user-images.githubusercontent.com/49422461/106581173-8b75c280-657d-11eb-978f-a11201ff4bda.png)

暂时我才看到第二章 ，后续我再补充

**Comment by youthlql** [comment]
> 第二章
> ![image](https://user-images.githubusercontent.com/49422461/106581173-8b75c280-657d-11eb-978f-a11201ff4bda.png)
> 
> 暂时我才看到第二章 ，后续我再补充

![image](https://user-images.githubusercontent.com/49017153/107005815-39c27780-67cb-11eb-9808-fc26ac078bc8.png)
已修复
