### ISSUE TITLE
并发对应课程

### ISSUE THREAD

**Issue by DawnSiu** [youthlql/JavaYouth#5]
大佬，我想问问你的多线程并发那块，对应的是哪个视频课程

**Comment by youthlql** [comment]
龙果，黑马，尚硅谷，还有几本书

**Comment by youthlql** [comment]
juc那点看的是龙果的，黑马和尚硅谷看的比较少，剩余是书和源码

**Comment by DawnSiu** [comment]
哇，那太感谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月10日(星期六) 中午11:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [youthlql/JavaYouth] 并发对应课程 (#5)





 
juc那点看的是龙果的，黑马和尚硅谷看的比较少，剩余是书和源码
