### ISSUE TITLE
jvm 垃圾回收器部分图挂了

### ISSUE THREAD

**Issue by codedawn** [youthlql/JavaYouth#6]
如标题

**Comment by youthlql** [comment]
已更新

**Comment by codedawn** [comment]
在线阅读的还没好，辛苦了

**Comment by youthlql** [comment]
我之前一起更新了，你可能是有缓存
![image](https://user-images.githubusercontent.com/49017153/114572442-1247c980-9caa-11eb-89ee-b5a1e7972508.png)
